// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyzdgtKiTOKXCPmSox5Kxxwcw7Pe2Gvig',
    appId: '1:825772727920:web:65240804600103bc86deb5',
    messagingSenderId: '825772727920',
    projectId: 'tukosalama-6762e',
    authDomain: 'tukosalama-6762e.firebaseapp.com',
    storageBucket: 'tukosalama-6762e.firebasestorage.app',
    measurementId: 'G-DFZ0506SQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAXKwpnb64AaAMQA55o37HSlWU1fBX6gQ',
    appId: '1:825772727920:android:b193f3e66f31660286deb5',
    messagingSenderId: '825772727920',
    projectId: 'tukosalama-6762e',
    storageBucket: 'tukosalama-6762e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeYr4ze9ZY_oakpnqzCpv4T1Zoa9YRJpk',
    appId: '1:825772727920:ios:c8a8f4ba373d12be86deb5',
    messagingSenderId: '825772727920',
    projectId: 'tukosalama-6762e',
    storageBucket: 'tukosalama-6762e.firebasestorage.app',
    iosBundleId: 'com.example.tukoSalama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeYr4ze9ZY_oakpnqzCpv4T1Zoa9YRJpk',
    appId: '1:825772727920:ios:c8a8f4ba373d12be86deb5',
    messagingSenderId: '825772727920',
    projectId: 'tukosalama-6762e',
    storageBucket: 'tukosalama-6762e.firebasestorage.app',
    iosBundleId: 'com.example.tukoSalama',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyzdgtKiTOKXCPmSox5Kxxwcw7Pe2Gvig',
    appId: '1:825772727920:web:29622e45f8ab0a6286deb5',
    messagingSenderId: '825772727920',
    projectId: 'tukosalama-6762e',
    authDomain: 'tukosalama-6762e.firebaseapp.com',
    storageBucket: 'tukosalama-6762e.firebasestorage.app',
    measurementId: 'G-LTG7N0VE7R',
  );
}
